### ISSUE TITLE
Using bonemeal causes crashes

### ISSUE THREAD

**Issue by UmbralSurvivor** [Builderdog841/Ancient-Aether#172] opened 2024-02-10 23:57 UTC
[crash-2024-02-10_12.55.12-client.txt](https://github.com/Builderdog841/Ancient-Aether/files/14230817/crash-2024-02-10_12.55.12-client.txt)
[crash-2024-02-10_17.52.29-client.txt](https://github.com/Builderdog841/Ancient-Aether/files/14230818/crash-2024-02-10_17.52.29-client.txt)
Both from right clicking with bonemeal in the overworld. There's a Sunroot tree nearby, might be a problem?

**Comment by Builderdog841** [comment] 2024-02-11 18:23
Very strange, I'll look into it

**Comment by Builderdog841** [comment] 2024-02-11 18:29
I can't reproduce this with AA alone installed so maybe there is something wrong with the Sunroot Tree

**Comment by Builderdog841** [comment] 2024-02-11 18:32
Maybe try updatingAncient Aether to v0.8.8?

**Comment by UmbralSurvivor** [comment] 2024-02-11 20:33
[crash-2024-02-11_14.30.53-client.txt](https://github.com/Builderdog841/Ancient-Aether/files/14233955/crash-2024-02-11_14.30.53-client.txt)

On 0.8.8. Doesn't happen when clicking air, only blocks.

Here's a list of installed mods; also, I'm on a server. The first crash I had with this crashed both server and player, the other 2 have crashed just my client.
[mods.txt](https://github.com/Builderdog841/Ancient-Aether/files/14233959/mods.txt)

**Comment by UmbralSurvivor** [comment] 2024-02-11 20:43
[crash-2024-02-11_14.41.18-client.txt](https://github.com/Builderdog841/Ancient-Aether/files/14233986/crash-2024-02-11_14.41.18-client.txt)
I tried to break all the Aether trees in my overworld base. I crashed when I used TreeChop to try and mine a Highsproot tree. I think I've found the issue

**Comment by UmbralSurvivor** [comment] 2024-02-12 19:20
It also crashes with items that apply the bonemeal effect, like Enigmatic Legcay's "Essence of Raging Life"

**Comment by Builderdog841** [comment] 2024-02-15 16:54
ngl no idea what caused this but I rewrote Log Stripping Code so it should be fixed now

**Closed by Builderdog841** 2024-02-15 16:54 UTC
Labels: type/bug, priority/high

**Comment by rrusciguy** [comment] 2024-02-17 15:44
Just popping in to say Ive had the same issue, trying to bonemeal a crop in the overworld without even having opened the aether caused a crash. Trace extensively mentioned this mod
[crash-2024-02-17_10.40.35-client.txt](https://github.com/Builderdog841/Ancient-Aether/files/14319323/crash-2024-02-17_10.40.35-client.txt)
